
spring:
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

queue:
   name: test   

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost