spring:
  cloud:
    gateway:
      routes:
      - id: department_service_route
        uri: http://localhost:9091
        predicates:
        - Cookie=myservice,department-service
      - id: user_service_route
        uri: http://localhost:9092
        predicates:
        - Cookie=myservice,user-service

# spring:
#   cloud:
#     gateway:
#       discovery.locator:
#         enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost