spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: post-service
            uri: lb://POST-SERVICE
            predicates:
              - Path=/post/**
            filters:
            - name: AuthorizationGatewayFilter
              args:
                preFilter: true
                postFilter: false
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
            - name: CircuitBreaker
              args:
                name: postServiceCircuitBreaker
                routeId: post-service
                fallbackUri: forward:/fallback/post-service
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user/**
            filters:
            - name: AuthorizationGatewayFilter
              args:
                preFilter: true
                postFilter: false
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                routeId: user-service
                fallbackUri: forward:/fallback/user-service
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "http://localhost:5173"
                allowedHeaders: "*"
                allowedMethods:
                - GET
                - POST
        

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

security:
   secret:
      hash: ${HASH_SECRET}
      jwt: ${JWT_SECRET_KEY}