spring:
  cloud:
    gateway:
      routes:
      - id: post-service
        uri: lb://POST-SERVICE
        predicates:
          - Path=/post/**
        
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost