spring:
  cloud:
    gateway:
      routes:
      - id: path_routes
        uri: http://localhost:9091
        predicates:
        - Path=/department-service/**

# spring:
#   cloud:
#     gateway:
#       discovery.locator:
#         enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost