
spring:
   #Mongo DB configurations
   data:
      mongodb:
         uri: ${MONGO_URI}

#Eureka Configurations
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: ${EUREKA_DEFAULTZONE}
   instance:
      hostname: localhost

#Actuator and prometheus configuration
management:
   endpoints:
      prometheus:
         enabled: true
      web:
         exposure:
            include:
               - info
               - health
               - metrics
   metrics:
      tags:
         application: POST-SERVICE

#AWS Configuration
aws:
   accessKey: ${AWS_ACCESS_KEY}
   secretKey: ${AWS_SECRET_KEY}
   region: ${AWS_REGION}
   snsArn: ${AWS_SNS_ARN}
   s3Bucket: ${AWS_S3_BUCKET}

security:
   secret:
      hash: ${HASH_SECRET}
   filters:
      hash-check:
         enabled: true
      gateway-auth:
         enabled: true
  
user:
   service:
      testEnvVariable: ${JAVA_HOME}