
spring:
   #Mongo DB configurations
   data:
      mongodb:
         # Changed password to "y4vF49W7TKLAvbQ1" as you have stupidely pushed the file on GitHub public repo
         uri: mongodb+srv://mayureshmarathe123:y4vF49W7TKLAvbQ1@maymarmongo.9yyskci.mongodb.net/PostService 

#Eureka Configurations
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost

#Actuator and prometheus configuration
management:
   endpoints:
      prometheus:
         enabled: true
      web:
         exposure:
            include:
               - info
               - health
               - metrics
   metrics:
      tags:
         application: POST-SERVICE