
spring:
   #Mongo DB configurations
   data:
      mongodb:
         uri: mongodb://mayureshmarathe123:2MdedbmKMsz8b9Eu@maymarmongo.9yyskci.mongodb.net/

#Eureka Configurations
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost

#Actuator and prometheus configuration
management:
   endpoints:
      prometheus:
         enabled: true
      web:
         exposure:
            include:
               - info
               - health
               - metrics
   metrics:
      tags:
         application: POST-SERVICE