spring:
   #Kafka configurations
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      batch-size: 16384
      properties:
        linger.ms: 100
        spring.json.add.type.headers: false
    consumer:
      group-id: review-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.microservices.posts.dto,com.microservices.reviews.dto"

   #Mongo DB configurations
  mongodb:
    uri: ${MONGO_REVIEWS_SERVICE_DBURI}

#Eureka Configurations
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULTZONE}
  instance:
    hostname: localhost

#Actuator and prometheus configuration
management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include:
          - info
          - health
          - metrics
  metrics:
    tags:
      application: POST-SERVICE

custom:
  security:
    policies:
      - path-expression: /review/api/v1/**
        service-names:
          - gateway-controller

security:
  filters:
    gateway-auth:
      enabled: true