
spring:
  #MySQL DB configurations
   datasource:
      url: ${USER_MICROSERVICE_MYSQL_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect

#Eureka Configurations
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: ${EUREKA_DEFAULTZONE}
   instance:
      hostname: localhost

#Actuator and prometheus configuration
management:
   tracing:
      sampling:
         probability: 1.0
   zipkin:
      tracing:
         endpoint: http://localhost:9411/api/v2/spans
   endpoints:
      prometheus:
         enabled: true
      web:
         exposure:
            include:
               - info
               - health
               - metrics
               - prometheus
   metrics:
      tags:
         application: USER-SERVICE

custom:
   security:
      policies:
         - path-expression: /user/api/v1/exists/**
           service-names:
              - follower-service
         - path-expression: /user/api/v1/**
           service-names:
              - gateway-controller
              
security:
   filters:
      gateway-auth:
         enabled: true